### ISSUE TITLE
Send your SHA1 key to Ben

### ISSUE THREAD

**Issue by benbek** [benbek/HereAStory-Android#11]
See email or [this link](https://developers.google.com/maps/documentation/android/start#display_your_apps_certificate_information) for more info.

**Comment by benbek** [comment]
@tussbaum?

**Comment by tussbaum** [comment]
what key is missing?

**Comment by benbek** [comment]
The key that is linked to the issue's contents. See the link and send me
back the key so the maps could be loaded to your device when you compile
and run the code.

**Comment by tussbaum** [comment]
Well, I'd never issue one. 
do you mean I need to issue all the play store certificates?

**Comment by benbek** [comment]
Just the debug certificate at this time.
In essence you should run this line on your OSX machine:
`keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android`
and send me by e-mail the line that starts with SHA1.

**Comment by tussbaum** [comment]
SHA1: 3F:0D:06:C8:6A:94:49:F3:E8:47:FA:27:9B:30:02:B7:FC:3B:9C:8C

**Comment by benbek** [comment]
Thanks. Will update it later on tonight.
